EVM fee proxy
futureversecom/trn-examples pull request #28
Opened 2023-07-20 17:48 UTC by KarishmaBothara

## Summary

WIP
_Details of the change in bullet points._

## Checklist

- [ ] Add description
- [ ] Tag related issue(s)

2023-07-23 20:14 UTC, aidan-starke requested changes
Looks good, can you please run `pnpm lint` and fix warnings, and remove extra examples from README

2023-07-24 02:59 UTC, vldolot commented on examples/evm/use-feeProxy/src/callWithFeePreferences.ts
> +	console.log("tokenBalanceUpdated::", tokenBalanceUpdated.toString());
Remove the double `::` (just use one `:`) to be consistent with the other examples' console.log style.

2023-07-24 03:00 UTC, vldolot commented on packages/utils/src/getAmountIn.ts
> +	console.log("result::", result);
Same here.

2023-07-24 03:11 UTC, vldolot commented on examples/evm/use-feeProxy/src/callWithFeePreferences.ts
> +		gasPrice: fees.gasPrice!,
Just a suggestion:
Can put the values for `data`, `gasLimit` and `gasPrice` into its own variable with the same name so you can do tha property shorthand, e.g.:
```js
const unsignedTx = {
  ...,
  nonce,
  data,
  gasLimit,
  gasPrice
};
```

2023-07-25 19:39 UTC, aidan-starke approved these changes

2023-07-25 19:40 UTC, merged